# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2228b20493a35fd1dca66ea30a7e20af70f5810b91821aeb172ec5e42daf8dd652e9c6ef487c737dd4795241c7ee0ffa912f9d101633f8579a2dc7a54c5b6f21

test:
  secret_key_base: 898424ca1193ec85d98776190ff1031c650cee59e4161dbc52244d0da23f219c5dd8ae65c9ad9a59ed6a507d8d4596a9540b7545bcf00883ac8f892b007e8a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
